//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectData.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ID&quot;;&quot;GebruikVanGeweld&quot;;&quot;SoortDiefstal&quot;;&quot;RegioS&quot;;&quot;Perioden&quot;;&quot;TotaalGeregistreerdeDiefstallen_1&quot;;&quot;GeregistreerdeDiefstallenRelatief_2&quot;;&quot;GeregistreerdeDiefstallenPer1000Inw_3&quot;;&quot;TotaalOpgehelderdeDiefstallen_4&quot;;&quot;OpgehelderdeDiefstallenRelatief_5&quot;;&quot;RegistratiesVanVerdachten_6&quot;
        ///&quot;48&quot;;&quot;0&quot;;&quot;00&quot;;&quot;PV20  &quot;;&quot;2010JJ00&quot;;&quot;   19640&quot;;&quot;     100&quot;;&quot;    34.1&quot;;&quot;    3525&quot;;&quot;    18.0&quot;;&quot;    4815&quot;
        ///&quot;49&quot;;&quot;0&quot;;&quot;00&quot;;&quot;PV20  &quot;;&quot;2011JJ00&quot;;&quot;   19415&quot;;&quot;     100&quot;;&quot;    33.5&quot;;&quot;    3525&quot;;&quot;    18.1&quot;;&quot;    4700&quot;
        ///&quot;50&quot;;&quot;0&quot;;&quot;00&quot;;&quot;PV20  &quot;;&quot;2012JJ00&quot;;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dataset_Diefstallen {
            get {
                return ResourceManager.GetString("Dataset_Diefstallen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ID&quot;;&quot;RegioS&quot;;&quot;Perioden&quot;;&quot;AantalPersonen_1&quot;;&quot;GemiddeldBesteedbaarInkomen_2&quot;;&quot;RangnummerBesteedbaarInkomen_3&quot;;&quot;GemiddeldGestandaardiseerdInkomen_4&quot;;&quot;RangnummerGestandaardiseerdInkomen_5&quot;;&quot;AantalPersonen_6&quot;;&quot;InVanPersonenMetEnZonderInkomen_7&quot;;&quot;GemiddeldPersoonlijkInkomen_8&quot;;&quot;RangnummerPersoonlijkInkomen_9&quot;;&quot;GemiddeldBesteedbaarInkomen_10&quot;;&quot;RangnummerBesteedbaarInkomen_11&quot;
        ///&quot;66&quot;;&quot;PV20  &quot;;&quot;2005JJ00&quot;;&quot;   574.0&quot;;&quot;    11.5&quot;;&quot;      11&quot;;&quot;    18.2&quot;;&quot;      12&quot;;&quot;   384.2&quot;;&quot;      67&quot;;&quot;    23.2&quot;;&quot;      12&quot;;&quot;    16.4&quot;;&quot;   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dataset_Gemiddeld_Inkomen {
            get {
                return ResourceManager.GetString("Dataset_Gemiddeld_Inkomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MainMenuBackground {
            get {
                object obj = ResourceManager.GetObject("MainMenuBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MainMenuBackgroundNoText {
            get {
                object obj = ResourceManager.GetObject("MainMenuBackgroundNoText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;TableInfos&quot;
        ///&quot;ID&quot;;&quot;Title&quot;;&quot;ShortTitle&quot;;&quot;Identifier&quot;;&quot;Summary&quot;;&quot;Modified&quot;;&quot;ReasonDelivery&quot;;&quot;ExplanatoryText&quot;;&quot;Language&quot;;&quot;Catalog&quot;;&quot;Frequency&quot;;&quot;Period&quot;;&quot;ShortDescription&quot;;&quot;Description&quot;;&quot;DefaultPresentation&quot;;&quot;DefaultSelection&quot;;&quot;GraphTypes&quot;;&quot;OutputStatus&quot;;&quot;Source&quot;;&quot;MetaDataModified&quot;;&quot;SearchPriority&quot;
        ///&quot;0&quot;;&quot;Geregistreerde diefstallen; diefstallen en verdachten, regio&quot;;&quot;Geregistreerde diefstallen, regio&quot;;&quot;83651NED&quot;;&quot;Geregistreerde en opgehelderde diefstallen; geregistreerde verdachten
        ///soort diefstal, regionale e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
    }
}
